name: GitHub Actions

on: [push]
jobs:
    Run-GitHub-Actions:
        runs-on: ubuntu-latest
    steps:
        -name: List Files
        run: |
            pwd
            ls -a
        -name: Checkout
         uses: actions/checkout@v2
            
